### ISSUE TITLE
initThreadPool freezes when compiling with -C lto flag

### ISSUE THREAD

**Issue by alordash** [GoogleChromeLabs/wasm-bindgen-rayon#27] opened 2022-05-06 17:20 UTC
I used default example without bundlers.
lib.rs:
```rust
use wasm_bindgen::prelude::*;
use rayon::prelude::*;
pub use wasm_bindgen_rayon::init_thread_pool;

#[wasm_bindgen]
pub fn sum(numbers: &[i32]) -> i32 {
    numbers.par_iter().sum()
}
```
index.html:
```html
<!DOCTYPE html>
<body>
    <script type="module">
        new Worker('worker.js', { type: 'module' });
    </script>
</body>
```
worker.js:
```js
import init, { sum, initThreadPool } from "./pkg/test.js";
console.log(`Worker created`);
init().then(_ => {
    console.log(`Initialized wasm`);
    initThreadPool(navigator.hardwareConcurrency).then(_ => {
        console.log(`Initialized thread pool`);
        let result = sum(new Int32Array([1, 2, 3]))
        console.log(result)
    })
})
```
Cargo.toml:
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen-rayon = { version = "1.0", features = ["no-bundler"] }
wasm-bindgen = "0.2.74"
rayon = "1.5"
```
Without `lto = true` everything works fine. However when I compile with `lto = true`, function `initThreadPool` freezes.
Output without link time optimization:
![Ok](https://user-images.githubusercontent.com/54469554/167181717-50a703af-5336-4e9e-9e1d-0ce4126a2347.jpg)
Output with link time optimization:
![Frozen](https://user-images.githubusercontent.com/54469554/167181409-b8a34691-fe88-4950-963a-cab2f3c3d175.jpg)

**Comment by RReverser** [comment] 2022-05-06 21:39
Huh, that's weird, I used wasm-bindgen-rayon myself in projects with LTO successfully, although it's been a while.

Can you / do you want to dig deeper into what's happening (e.g. add some logging etc.)? If not, I'll try to get to this, but might take some time.

**Comment by alordash** [comment] 2022-05-06 21:47
I fear my research will not be fruitful, as I'm still newbie in rust. I found this bug (?) by accident, just wanted to share it.

**Comment by RReverser** [comment] 2022-05-08 21:03
Ok at least I can reproduce (unfortunately)...

**Comment by RReverser** [comment] 2022-05-10 13:08
Or maybe on rayon side.

**Comment by alexcrichton** [comment] 2022-05-10 15:32
I have not seen this specifically before, but in my experience 99% of bugs that arise from turning LTO on are legitimate bugs that don't need LTO to reproduce, it just happens to expose it.

**Comment by RReverser** [comment] 2022-05-10 16:08
Heh, if it's true, the problem is that it's hard (for now, impossible) to reproduce this bug without LTO, and with LTO it's hard to debug because the code is heavily optimized.

So far it appears the bug is somewhere inside Rayon itself, as all my logs indicate at its internal mutexes hanging, which makes debugging even harder still.

**Comment by ashtyn3** [comment] 2022-05-22 20:40
Any update on this issue?

**Comment by RReverser** [comment] 2022-05-23 08:50
If there would be an update, it would be posted in comments, so no.

As I said above, I don't know what's going on here, but you might have more luck if you want to try!

**Comment by RReverser** [comment] 2022-12-30 04:21
Hm, I just tried again and can't reproduce this anymore. Given that the pinned Rust version hasn't changed, I suspect it must've been either a bug in wasm-bindgen or in Chrome itself (I think neither of us tested in other browsers?)...

I don't like mysteries that disappear on their own, but given that it did, I'll close this issue for now.

**Closed by RReverser** 2022-12-30 04:21 UTC
Labels: bug
