### ISSUE TITLE
Is it possible to initialize thread pool from rust side?

### ISSUE THREAD

**Issue by felipellrocha** [GoogleChromeLabs/wasm-bindgen-rayon#29] opened 2022-06-16 01:27 UTC
I (believe) one needs to initialize the thread pool on a separate thread itself. Is it possible to initialize the thread pool from the rust side using something like `wasm_thread` (https://github.com/chemicstry/wasm_thread) to spin up the thread that initializes the pool?

**Comment by jmadotgg** [comment] 2022-08-07 10:07
Yeah, that would be great!

**Comment by jmadotgg** [comment] 2022-08-14 18:32
Okay, probably a duplicate of https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/issues/12.

**Comment by RReverser** [comment] 2022-08-14 20:21
Indeed. If there is enough interest, I suppose we could expose it under a feature flag, but I'm hesitant of making the base crate larger (due to async machinery) for a minor convenience.

**Closed** 2024-01-17 20:59 UTC
